// Package types provides core data types for the Kraken SDK.
package types

import (
	"github.com/shopspring/decimal"
)

// OrderType represents the execution model of an order.
type OrderType string

const (
	OrderTypeMarket            OrderType = "market"
	OrderTypeLimit             OrderType = "limit"
	OrderTypeIceberg           OrderType = "iceberg"
	OrderTypeStopLoss          OrderType = "stop-loss"
	OrderTypeStopLossLimit     OrderType = "stop-loss-limit"
	OrderTypeTakeProfit        OrderType = "take-profit"
	OrderTypeTakeProfitLimit   OrderType = "take-profit-limit"
	OrderTypeTrailingStop      OrderType = "trailing-stop"
	OrderTypeTrailingStopLimit OrderType = "trailing-stop-limit"
	OrderTypeSettlePosition    OrderType = "settle-position"
)

// Side represents the order direction.
type Side string

const (
	SideBuy  Side = "buy"
	SideSell Side = "sell"
)

// TimeInForce specifies how long an order remains in effect.
type TimeInForce string

const (
	// TIFGoodTilCanceled - order remains until cancelled.
	TIFGoodTilCanceled TimeInForce = "GTC"
	// TIFGoodTilDate - order remains until specified date.
	TIFGoodTilDate TimeInForce = "GTD"
	// TIFImmediateOrCancel - execute immediately or cancel.
	TIFImmediateOrCancel TimeInForce = "IOC"
)

// OrderStatus describes the current state of an order.
type OrderStatus string

const (
	OrderStatusPendingNew      OrderStatus = "pending_new"
	OrderStatusNew             OrderStatus = "new"
	OrderStatusOpen            OrderStatus = "open"
	OrderStatusPartiallyFilled OrderStatus = "partially_filled"
	OrderStatusFilled          OrderStatus = "filled"
	OrderStatusCanceled        OrderStatus = "canceled"
	OrderStatusExpired         OrderStatus = "expired"
	OrderStatusClosed          OrderStatus = "closed"
)

// TriggerType represents the reference price for triggered orders.
type TriggerType string

const (
	TriggerLast  TriggerType = "last"
	TriggerIndex TriggerType = "index"
)

// PriceType represents the unit type for trigger/limit prices.
type PriceType string

const (
	PriceTypeStatic PriceType = "static"
	PriceTypePct    PriceType = "pct"
	PriceTypeQuote  PriceType = "quote"
)

// STPType represents Self Trade Prevention modes.
type STPType string

const (
	STPCancelNewest STPType = "cancel-newest"
	STPCancelOldest STPType = "cancel-oldest"
	STPCancelBoth   STPType = "cancel-both"
)

// OrderFlags represents order flags.
type OrderFlags string

const (
	// FlagPostOnly - post-only order (maker only).
	FlagPostOnly OrderFlags = "post"
	// FlagFeeInBase - prefer fee in base currency.
	FlagFeeInBase OrderFlags = "fcib"
	// FlagFeeInQuote - prefer fee in quote currency.
	FlagFeeInQuote OrderFlags = "fciq"
	// FlagVolumeInQuote - volume expressed in quote currency.
	FlagVolumeInQuote OrderFlags = "viqc"
)

// Triggers contains trigger price parameters for stop/trailing orders.
type Triggers struct {
	// Reference is the price to track for triggering ("index" or "last").
	Reference TriggerType `json:"reference,omitempty"`

	// Price is the trigger price amount.
	Price decimal.Decimal `json:"price"`

	// PriceType is the unit type ("static", "pct", "quote").
	PriceType PriceType `json:"price_type,omitempty"`

	// ActualPrice is the current effective trigger price.
	ActualPrice *decimal.Decimal `json:"actual_price,omitempty"`

	// PeakPrice is the peak/trough price for trailing orders.
	PeakPrice *decimal.Decimal `json:"peak_price,omitempty"`

	// LastPrice is the reference price that triggered the order.
	LastPrice *decimal.Decimal `json:"last_price,omitempty"`

	// Status is the trigger status ("triggered" or "untriggered").
	Status string `json:"status,omitempty"`

	// Timestamp is when the trigger activated.
	Timestamp *UnixTime `json:"timestamp,omitempty"`
}

// Conditional contains parameters for OTO (One-Triggers-Other) orders.
type Conditional struct {
	// OrderType is the type of the secondary close order.
	OrderType OrderType `json:"order_type"`

	// LimitPrice is the limit price for the secondary order.
	LimitPrice *decimal.Decimal `json:"limit_price,omitempty"`

	// LimitPriceType is the unit type for the limit price.
	LimitPriceType PriceType `json:"limit_price_type,omitempty"`

	// TriggerPrice is the trigger price for triggered secondary orders.
	TriggerPrice *decimal.Decimal `json:"trigger_price,omitempty"`

	// TriggerPriceType is the unit type for the trigger price.
	TriggerPriceType PriceType `json:"trigger_price_type,omitempty"`
}

// Order represents an order in the Kraken system.
type Order struct {
	// OrderID is the unique order identifier generated by Kraken.
	OrderID string `json:"order_id"`

	// ClientOrderID is an optional client-specified identifier.
	ClientOrderID string `json:"cl_ord_id,omitempty"`

	// UserRef is an optional numeric identifier specified by client.
	UserRef int64 `json:"userref,omitempty"`

	// RefID is the referral order transaction ID that created this order.
	RefID string `json:"refid,omitempty"`

	// Symbol is the trading pair (e.g., "BTC/USD").
	Symbol string `json:"symbol"`

	// Pair is the trading pair (REST API format, e.g., "XXBTZUSD").
	Pair string `json:"pair,omitempty"`

	// Side is the order direction (buy/sell).
	Side Side `json:"side"`

	// OrderType is the execution model.
	OrderType OrderType `json:"order_type"`

	// OrderQty is the order quantity in base asset.
	OrderQty decimal.Decimal `json:"order_qty"`

	// Volume is the order volume (REST API format).
	Volume decimal.Decimal `json:"vol,omitempty"`

	// LimitPrice is the limit price for limit orders.
	LimitPrice *decimal.Decimal `json:"limit_price,omitempty"`

	// Price is the primary price (REST API format).
	Price *decimal.Decimal `json:"price,omitempty"`

	// Price2 is the secondary price (REST API format).
	Price2 *decimal.Decimal `json:"price2,omitempty"`

	// TimeInForce specifies how long the order remains in effect.
	TimeInForce TimeInForce `json:"time_in_force,omitempty"`

	// Status is the current order status.
	Status OrderStatus `json:"order_status"`

	// CumQty is the cumulative executed quantity.
	CumQty decimal.Decimal `json:"cum_qty"`

	// VolumeExec is the volume executed (REST API format).
	VolumeExec decimal.Decimal `json:"vol_exec,omitempty"`

	// CumCost is the cumulative executed value.
	CumCost decimal.Decimal `json:"cum_cost"`

	// Cost is the total cost (REST API format).
	Cost decimal.Decimal `json:"cost,omitempty"`

	// AvgPrice is the average fill price.
	AvgPrice decimal.Decimal `json:"avg_price"`

	// Fee is the total fee paid.
	Fee decimal.Decimal `json:"fee,omitempty"`

	// Margin indicates if the order is funded on margin.
	Margin bool `json:"margin,omitempty"`

	// PostOnly indicates if the order is post-only.
	PostOnly bool `json:"post_only,omitempty"`

	// ReduceOnly indicates if the order can only reduce position.
	ReduceOnly bool `json:"reduce_only,omitempty"`

	// Leverage is the leverage amount.
	Leverage string `json:"leverage,omitempty"`

	// Triggers contains trigger parameters for stop/trailing orders.
	Triggers *Triggers `json:"triggers,omitempty"`

	// Conditional contains parameters for OTO orders.
	Conditional *Conditional `json:"conditional,omitempty"`

	// OpenTime is when the order was placed.
	OpenTime UnixTime `json:"opentm,omitempty"`

	// StartTime is the scheduled start time.
	StartTime *UnixTime `json:"starttm,omitempty"`

	// ExpireTime is the expiration time.
	ExpireTime *UnixTime `json:"expiretm,omitempty"`

	// Timestamp is the last update timestamp.
	Timestamp UnixTime `json:"timestamp,omitempty"`

	// Description contains order description info.
	Description *OrderDescription `json:"descr,omitempty"`

	// Misc contains miscellaneous info flags.
	Misc string `json:"misc,omitempty"`

	// OFlags contains order flags.
	OFlags string `json:"oflags,omitempty"`

	// Trades contains related trade IDs.
	Trades []string `json:"trades,omitempty"`
}

// OrderDescription contains human-readable order description.
type OrderDescription struct {
	// Pair is the asset pair.
	Pair string `json:"pair"`

	// Type is the order direction (buy/sell).
	Type string `json:"type"`

	// OrderType is the order type.
	OrderType string `json:"ordertype"`

	// Price is the primary price.
	Price string `json:"price"`

	// Price2 is the secondary price.
	Price2 string `json:"price2"`

	// Leverage is the leverage amount.
	Leverage string `json:"leverage"`

	// Order is the full order description string.
	Order string `json:"order"`

	// Close is the conditional close description.
	Close string `json:"close,omitempty"`
}

// Execution represents an execution/fill event.
type Execution struct {
	// ExecID is the execution identifier.
	ExecID string `json:"exec_id"`

	// OrderID is the related order identifier.
	OrderID string `json:"order_id"`

	// TradeID is the trade identifier.
	TradeID int64 `json:"trade_id"`

	// Symbol is the trading pair.
	Symbol string `json:"symbol"`

	// Side is the order side.
	Side Side `json:"side"`

	// ExecType describes the type of execution event.
	ExecType string `json:"exec_type"`

	// LastQty is the quantity filled in this execution.
	LastQty decimal.Decimal `json:"last_qty"`

	// LastPrice is the price of this execution.
	LastPrice decimal.Decimal `json:"last_price"`

	// Cost is the value of this execution.
	Cost decimal.Decimal `json:"cost"`

	// Fees contains fees paid.
	Fees []ExecutionFee `json:"fees,omitempty"`

	// LiquidityInd indicates maker ("m") or taker ("t").
	LiquidityInd string `json:"liquidity_ind,omitempty"`

	// Timestamp is the execution timestamp.
	Timestamp UnixTime `json:"timestamp"`
}

// ExecutionFee represents a fee in an execution.
type ExecutionFee struct {
	// Asset is the fee currency.
	Asset string `json:"asset"`

	// Qty is the fee amount.
	Qty decimal.Decimal `json:"qty"`
}
